config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  resources :posts
  resources :users
  resources :articles
  resources :user_sessions

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  get 'welcome/index'

  root :to => 'welcome#index'  # redirect to the welcome page

  get 'examples/form'

  post 'examples/form'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld - application Layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<h1>Codigo Facilito</h1>
</header>
<!--This execute the page that we structured and insert here into the layout -->

<nav class='navbar'>
	<div class='navbar-inner'>
		<ul>
			<li><%= link_to 'Inicio', root_path %></li>
			<li><%= link_to 'Posts', posts_path %></li>
			<li><%=  current_user %></li>
			<% if current_user %>
				<li><%= link_to 'Nuevo articulo', new_article_path %></li>
				<li><%= link_to 'Log out #{current_user.username}', logout_path, method: :delete %></li>
				<li><%= link_to 'Editar Usuario', edit_usuario_path(current_user) %></li>
			<% else %>
				<li><%= link_to 'log in', login_path %></li>
			<% end %>
		</ul>
	</div>
</nav>

<%= yield %>

</body>
</html>

app/views/layouts/ejemplo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ejemplo Layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<h1>Ejemplo Layout</h1>
</header>
<!--This execute the page that we structured and insert here into the layout -->
<%= yield %>
<p>This message comes from the ejemplo layout</p>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome Layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<h1>Welcome Layout</h1>
</header>
<!--This execute the page that we structured and insert here into the layout -->
<%= yield %>

</body>
</html>